# Generated by Django 4.0.8 on 2023-01-12 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='favourite_titles',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
